# Generated by Django 4.2.6 on 2023-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='jhhh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
